export const ExchangeLinks = [
  {
    image: 'whitebit.png',
    title: 'WhiteBIT',
    trade: 'VRSC/BTC, VRSC/EUR, VRSC/USD',
    kyc: 'No KYC (2 BTC limit)',
    URI: 'https://whitebit.com/referral/VerusFoundation',
    URIText: 'WhiteBIT',
  },
  {
    image: 'stex.svg',
    title: 'Stex',
    trade: 'VRSC/BTC',
    kyc: '',
    URI: 'https://app.stex.com/en/trade/pair/BTC/VRSC',
    URIText: 'STEX',
  },
  {
    image: 'safetrade.png',
    title: 'SafeTrade',
    trade: 'VRSC/BTC',
    kyc: 'No KYC',
    URI: 'https://safe.trade/trading/vrscbtc',
    URIText: 'SafeTrade',
  },
  {
    image: 'aacoin.svg',
    title: 'AACoin',
    trade: 'VRSC/BTC',
    kyc: '',
    URI: 'https://www.aacoin.com/trade/VRSC_BTC',
    URIText: 'AAcoin',
  },
  {
    image: 'atomicdex.svg',
    title: 'AtomicDex',
    trade: 'All pairs',
    kyc: '',
    URI: 'https://atomicdex.io/',
    URIText: 'AtomicDex',
  },
  {
    image: 'graviex.svg',
    title: 'Graviex',
    trade: 'VRSC/BTC, VRSC/KMD, VRSC/USD',
    kyc: '',
    URI: 'https://graviex.net/markets/vrscbtc',
    URIText: 'Graviex',
  },
];
