export const ExchangeLinks = [
  {
    image: 'whitebit.png',
    title: 'WhiteBIT',
    trade: 'VRSC/BTC, VRSC/EUR, VRSC/USD',
    kyc: 'No KYC (2 BTC limit)',
    URI: 'https://whitebit.com/referral/VerusFoundation',
    URIText: 'whitebit.com',
  },
  {
    image: 'stex.svg',
    title: 'Stex',
    trade: 'VRSC/BTC',
    kyc: '',
    URI: 'https://app.stex.com/en/trade/pair/BTC/VRSC',
    URIText: 'stex.com',
  },
  {
    image: 'safetrade.png',
    title: 'SafeTrade',
    trade: 'VRSC/BTC',
    kyc: 'No KYC',
    URI: 'https://safe.trade/trading/vrscbtc',
    URIText: 'safe.trade',
  },
  {
    image: 'atomicdex.svg',
    title: 'AtomicDex',
    trade: 'All pairs',
    kyc: '',
    URI: 'https://atomicdex.io/',
    URIText: 'atomicdex.io',
  },
  {
    image: 'graviex.svg',
    title: 'Graviex',
    trade: 'VRSC/BTC, VRSC/KMD, VRSC/USD',
    kyc: '',
    URI: 'https://graviex.net/markets/vrscbtc',
    URIText: 'graviex.net',
  },
];
