import Menu from '../../components/Menu';
import FooterMenu from '../../components/FooterMenu';
import { miningStakingLinks } from '../../constants/miningStaking';

const Pools = () => {
  return (
    <>
      <div className="container grid max-w-5xl grid-cols-1 gap-6 mt-8 md:grid-cols-4">
        <div className="">
          <Menu pathList={miningStakingLinks} href="/mining-and-staking" />
        </div>
        <div className="max-w-5xl p-6 md:col-span-3">
          <h1 className="p-0 m-0 text-4xl font-normal">Pools</h1>
          <p className="leading-normal  font-p">
            Choose from a growing list of community pools. Direct any questions
            to the appropriate pool operator in the #pools channel on{' '}
            <a href="https://discord.gg/VRKMP2S" target="_blank">
              Discord
            </a>
            .
          </p>
          <h2 className="mt-16 text-2xl font-normal">Mining Pools</h2>
          <p className="leading-normal  font-p">
            Check how much hashrate is generated by every individual pool at{' '}
            <a href="https://miningpoolstats.stream/veruscoin" target="_blank">
              MiningPoolStats
            </a>
            .
          </p>
          <table className="w-3/4 border-collapse table-fixed font-p md:w-1/2">
            <thead>
              <tr>
                <th className="w-3/4 px-4 py-2"></th>
                <th className="w-1/4 px-4 py-2 text-center">Fee</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="w-3/4 px-4 py-2">
                  <a href="https://pool.veruscoin.io/" target="_blank">
                    VerusCoin Pool
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center">5%</td>
              </tr>
              <tr className="bg-gray-100">
                <td className="w-3/4 px-4 py-2">
                  <a href="http://vrsc.lepool.com.cn:8088/" target="_blank">
                    LePool
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center ">1%</td>
              </tr>
              <tr>
                <td className="w-3/4 px-4 py-2 ">
                  <a href="https://luckpool.net/verus/" target="_blank">
                    LuckPool
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center ">1%</td>
              </tr>
              <tr className="bg-gray-100">
                <td className="w-3/4 px-4 py-2">
                  <a href="https://zergpool.com/" target="_blank">
                    ZergPool
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center ">0.5%</td>
              </tr>
              <tr>
                <td className="w-3/4 px-4 py-2 ">
                  <a href="https://vrsc.ciscotech.dk/" target="_blank">
                    CiscoTech
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center ">1%</td>
              </tr>
            </tbody>
          </table>
          <h2 className="mt-16 text-2xl font-normal">Staking Pools</h2>

          <table className="w-3/4 mb-32 border-collapse table-fixed font-p md:w-1/2">
            <thead>
              <tr>
                <th className="w-3/4 px-4 py-2 "></th>
                <th className="w-1/4 px-4 py-2 text-center">Fee</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="w-3/4 px-4 py-2">
                  <a href="https://discord.gg/4FJJRY5" target="_blank">
                    Ginasis
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center">5%</td>
              </tr>
              <tr className="bg-gray-100">
                <td className="w-3/4 px-4 py-2">
                  <a
                    href="https://docs.google.com/spreadsheets/d/1Up1WbMuCR21e6TxLae6zjLJePu_RIOVZwqShRj9vVvc/edit?usp=sharing"
                    target="_blank"
                  >
                    DudezMobi
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center ">1%</td>
              </tr>
              <tr>
                <td className="w-3/4 px-4 py-2">
                  <a
                    href="https://www.aacoin.com/#/trade?symbol=VRSC_BTC"
                    target="_blank"
                  >
                    AAcoin Exchange
                  </a>
                </td>
                <td className="w-1/4 px-4 py-2 text-center">20%</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <FooterMenu
        hrefLocation="/mining-and-staking"
        pathList={miningStakingLinks}
      />
    </>
  );
};

export default Pools;
