import Menu from '../../components/Menu';
import FooterMenu from '../../components/FooterMenu';
import { miningStakingLinks } from '../../constants/miningStaking';
import { NextSeo } from 'next-seo';

const Pools = () => {
  return (
    <>
      <NextSeo
        title="Pools"
        description="Choose from a growing list of community pools."
        additionalMetaTags={[
          {
            name: 'keywords',
            content:
              'verus, ERC-20, VRSC, earn, mining, staking, pools, network economy, secure, mining pools',
          },
        ]}
      />
      <div className="container grid max-w-5xl grid-cols-1 gap-6 mt-8 md:grid-cols-4">
        <div className="">
          <Menu pathList={miningStakingLinks} href="/mining-and-staking" />
        </div>
        <div className="max-w-5xl p-6 md:col-span-3">
          <h1 className="p-0 m-0 text-2xl font-normal md:text-4xl">Pools</h1>
          <p className="my-8">
            Choose from a growing list of community pools. Direct any questions
            to the appropriate pool operator in the #pools channel on{' '}
            <a
              href="https://discord.gg/VRKMP2S"
              target="_blank"
              className="underline external"
            >
              Discord
            </a>
            .
          </p>
          <h2 className="mt-16 text-2xl font-normal">Mining Pools</h2>
          <p className="my-8">
            Check how much hashrate is generated by every individual pool at{' '}
            <a
              href="https://miningpoolstats.stream/veruscoin"
              target="_blank"
              className="underline external"
            >
              MiningPoolStats
            </a>
            .
          </p>
          <table className="w-3/4 border-collapse table-fixed font-p md:w-1/2">
            <thead>
              <tr>
                <th className="w-3/4 p-4"></th>
                <th className="w-1/4 p-4 text-center">Fee</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="w-3/4 p-4">
                  <a href="https://pool.veruscoin.io/" target="_blank">
                    VerusCoin Pool
                  </a>
                </td>
                <td className="w-1/4 p-4 text-center">5%</td>
              </tr>
              <tr className="bg-gray-100">
                <td className="w-3/4 p-4">
                  <a href="http://vrsc.lepool.com.cn:8088/" target="_blank">
                    LePool
                  </a>
                </td>
                <td className="w-1/4 p-4 text-center ">1%</td>
              </tr>
              <tr>
                <td className="w-3/4 p-4 ">
                  <a href="https://luckpool.net/verus/" target="_blank">
                    LuckPool
                  </a>
                </td>
                <td className="w-1/4 p-4 text-center ">1%</td>
              </tr>
              <tr className="bg-gray-100">
                <td className="w-3/4 p-4">
                  <a href="https://zergpool.com/" target="_blank">
                    ZergPool
                  </a>
                </td>
                <td className="w-1/4 p-4 text-center ">0.5%</td>
              </tr>
              <tr>
                <td className="w-3/4 p-4 ">
                  <a href="https://vrsc.ciscotech.dk/" target="_blank">
                    CiscoTech
                  </a>
                </td>
                <td className="w-1/4 p-4 text-center ">1%</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <FooterMenu
        hrefLocation="/mining-and-staking"
        pathList={miningStakingLinks}
      />
    </>
  );
};

export default Pools;
